apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "demo-app"
        static_configs:
          - targets: ["demo-app:5000"]

      - job_name: "node-exporter"
        static_configs:
          - targets: ["node-exporter:9100"]

